name: fitness_app
description: App de fitness con rutinas inteligentes personalizadas
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Arquitectura y Estado
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4

  # Base de datos local
  sqflite: ^2.3.0
  path: ^1.8.3

  # Navegación
  go_router: ^12.1.1

  # Utilidades
  intl: ^0.18.1
  uuid: ^4.1.0

  # UI
  cupertino_icons: ^1.0.2

  dartz: ^0.10.1  # Para Either<Failure, Success>

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true